#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <string.h>
#include <algorithm>
#include <map>
#include <vector>
#include <thread>
#include <iostream>
#include <sstream>
#include <thread>
#include <map>
#include <time.h>
#include <fstream>

void writeLog(char *msg)
{
    time_t rawtime;
    time(&rawtime);
    std::ofstream outfile;
    outfile.open("clientlog.txt", std::ios::app);
    outfile << ctime(&rawtime);
    outfile << msg;
    outfile << '\n';
    outfile << '\n';
}

// Threaded function for handling responss from server
void listenServer(int serverSocket)
{
    int nread;         // Bytes read from socket
    char buffer[1025]; // Buffer for reading input

    while (true)
    {
        memset(buffer, 0, sizeof(buffer));
        nread = read(serverSocket, buffer, sizeof(buffer));

        if (nread < 0) // Server has dropped us
        {
            printf("Over and Out\n");
            exit(0);
        }
        else if (nread > 0)
        {
            printf("%s\n", buffer);
            //writeLog(buffer);

        }
    }
}

int main(int argc, char *argv[])
{
    struct addrinfo hints, *svr;    // Network host entry for server
    struct sockaddr_in server_addr; // Socket address for server
    int serverSocket;               // Socket used for server
    int nwrite;                     // No. bytes written to server
    char buffer[1025];              // buffer for writing to server
    bool finished;
    int set = 1; // Toggle for setsockopt

    if (argc != 3)
    {
        printf("Usage: chat_client <ip  port>\n");
        printf("Ctrl-C to terminate\n");
        exit(0);
    }

    std::cout << "Client commands are following" << std::endl;
    std::cout << "-----------------------------" << std::endl;
    std::cout << "Send autogenerated msg to the server:             <SENDMSG,TO_GROUP> {auto generates a msg}" << std::endl;
    std::cout << "Send custom msg to the server:                    <SENDMSG,TO_GROUP,MSG> {type in a custom msg}" << std::endl;
    std::cout << "Send to another server autogenerated msg:         <SENDTOSERVER,TO_GROUP> {auto generates a msg}" << std::endl;
    std::cout << "Send to another server custom msg:                <SENDMSG,TO_GROUP,MSG>" << std::endl;
    std::cout << "Get a msg from the server:                        <GETMSG,FROM_GROUP>" << std::endl;
    std::cout << "Get a msg from another server:                    <GETMSGTOSERVER,TO_GROUP,FROM_GROUP>" << std::endl;
    std::cout << "Connect the server to another server:             <CONNECT,TO_IP,TO_PORT>" << std::endl;
    std::cout << "List's servers that are connected to the server:  <LISTSERVERS>" << std::endl;
    std::cout << "Leave command sent to another server:             <LEAVE,TO_GROUP>" << std::endl;
    std::cout << "Status request sent to another server:            <STATUSREQ,TO_GROUP>" << std::endl;
    std::cout << "-----------------------------" << std::endl;

    memset(&hints, 0, sizeof(hints));

    hints.ai_family = AF_INET; // IPv4 only addresses
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_flags = AI_PASSIVE;

    if (getaddrinfo(argv[1], argv[2], &hints, &svr) != 0)
    {
        perror("getaddrinfo failed: ");
        exit(0);
    }

    serverSocket = socket(svr->ai_family, svr->ai_socktype, svr->ai_protocol);

    // Turn on SO_REUSEADDR to allow socket to be quickly reused after
    // program exit.

    if (setsockopt(serverSocket, SOL_SOCKET, SO_REUSEADDR, &set, sizeof(set)) < 0)
    {
        printf("Failed to set SO_REUSEADDR for port %s\n", argv[2]);
        perror("setsockopt failed: ");
    }

    if (connect(serverSocket, svr->ai_addr, svr->ai_addrlen) < 0)
    {
        printf("Failed to open socket to server: %s\n", argv[1]);
        perror("Connect failed: ");
        exit(0);
    }

    // Listen and print replies from server
    std::thread serverThread(listenServer, serverSocket);

    finished = false;
    while (!finished)
    {
        bzero(buffer, sizeof(buffer));

        fgets(buffer, sizeof(buffer), stdin);

        nwrite = send(serverSocket, buffer, strlen(buffer), 0);

        if (nwrite == -1)
        {
            perror("send() to server failed: ");
            finished = true;
        }
    }
}